package vn.com.payment.entities;
// Generated May 29, 2021 11:20:25 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "branch", catalog = "db_fintech")
public class Branch implements java.io.Serializable {

	private Integer rowId;
	private String branchName;
	private String manager;
	private String phone;
	private String address;
	private int status;
	private String bankAccountName;
	private String bankNote;
	private String bankMessageTransfer;
	private String bankMessageEg;
	private String hotline;

	public Branch() {
	}

	public Branch(String branchName, String manager, String phone, String address, int status, String bankAccountName,
			String bankNote, String bankMessageTransfer, String bankMessageEg, String hotline) {
		this.branchName = branchName;
		this.manager = manager;
		this.phone = phone;
		this.address = address;
		this.status = status;
		this.bankAccountName = bankAccountName;
		this.bankNote = bankNote;
		this.bankMessageTransfer = bankMessageTransfer;
		this.bankMessageEg = bankMessageEg;
		this.hotline = hotline;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "branch_name", nullable = false, length = 500)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "manager", nullable = false, length = 200)
	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address", nullable = false, length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "bank_account_name", nullable = false, length = 50)
	public String getBankAccountName() {
		return this.bankAccountName;
	}

	public void setBankAccountName(String bankAccountName) {
		this.bankAccountName = bankAccountName;
	}

	@Column(name = "bank_note", nullable = false, length = 5000)
	public String getBankNote() {
		return this.bankNote;
	}

	public void setBankNote(String bankNote) {
		this.bankNote = bankNote;
	}

	@Column(name = "bank_message_transfer", nullable = false, length = 500)
	public String getBankMessageTransfer() {
		return this.bankMessageTransfer;
	}

	public void setBankMessageTransfer(String bankMessageTransfer) {
		this.bankMessageTransfer = bankMessageTransfer;
	}

	@Column(name = "bank_message_eg", nullable = false, length = 500)
	public String getBankMessageEg() {
		return this.bankMessageEg;
	}

	public void setBankMessageEg(String bankMessageEg) {
		this.bankMessageEg = bankMessageEg;
	}

	@Column(name = "hotline", nullable = false, length = 15)
	public String getHotline() {
		return this.hotline;
	}

	public void setHotline(String hotline) {
		this.hotline = hotline;
	}

}
