package vn.com.payment.entities;
// Generated May 18, 2021 12:51:34 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GroupRoles generated by hbm2java
 */
@Entity
@Table(name = "group_roles", catalog = "db_fintech")
public class GroupRoles implements java.io.Serializable {

	private Integer rowId;
	private String name;
	private int status;
	private int orderMenu;

	public GroupRoles() {
	}

	public GroupRoles(String name, int status, int orderMenu) {
		this.name = name;
		this.status = status;
		this.orderMenu = orderMenu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "order_menu", nullable = false)
	public int getOrderMenu() {
		return this.orderMenu;
	}

	public void setOrderMenu(int orderMenu) {
		this.orderMenu = orderMenu;
	}

}
