package vn.com.payment.entities;
// Generated May 17, 2021 11:02:56 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubPermission generated by hbm2java
 */
@Entity
@Table(name = "sub_permission", catalog = "db_fintech")
public class SubPermission implements java.io.Serializable {

	private Integer rowId;
	private String name;
	private String alias;

	public SubPermission() {
	}

	public SubPermission(String name, String alias) {
		this.name = name;
		this.alias = alias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "alias", nullable = false, length = 200)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}


}
