package vn.com.payment.entities;
// Generated May 19, 2021 11:20:55 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblImages generated by hbm2java
 */
@Entity
@Table(name = "tbl_images", catalog = "db_fintech")
public class TblImages implements java.io.Serializable {

	private Long imageId;
	private int loanRequestDetailId;
	private Integer imageType;
	private String imageByte;
	private String imageUrl;
	private Integer imageIsFront;

	public TblImages() {
	}

	public TblImages(int loanRequestDetailId) {
		this.loanRequestDetailId = loanRequestDetailId;
	}

	public TblImages(int loanRequestDetailId, Integer imageType, String imageByte, String imageUrl,
			Integer imageIsFront) {
		this.loanRequestDetailId = loanRequestDetailId;
		this.imageType = imageType;
		this.imageByte = imageByte;
		this.imageUrl = imageUrl;
		this.imageIsFront = imageIsFront;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "image_id", unique = true, nullable = false)
	public Long getImageId() {
		return this.imageId;
	}

	public void setImageId(Long imageId) {
		this.imageId = imageId;
	}

	@Column(name = "loan_request_detail_id", nullable = false)
	public int getLoanRequestDetailId() {
		return this.loanRequestDetailId;
	}

	public void setLoanRequestDetailId(int loanRequestDetailId) {
		this.loanRequestDetailId = loanRequestDetailId;
	}

	@Column(name = "image_type")
	public Integer getImageType() {
		return this.imageType;
	}

	public void setImageType(Integer imageType) {
		this.imageType = imageType;
	}

	@Column(name = "image_byte")
	public String getImageByte() {
		return this.imageByte;
	}

	public void setImageByte(String imageByte) {
		this.imageByte = imageByte;
	}

	@Column(name = "image_url", length = 500)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "image_is_front")
	public Integer getImageIsFront() {
		return this.imageIsFront;
	}

	public void setImageIsFront(Integer imageIsFront) {
		this.imageIsFront = imageIsFront;
	}

}
