package vn.com.payment.entities;
// Generated 25-May-2021 21:30:25 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblLoanBill generated by hbm2java
 */
@Entity
@Table(name = "tbl_loan_bill", catalog = "db_fintech")
public class TblLoanBill implements java.io.Serializable {

	private Integer billId;
	private int loanId;
	private long loanRemainAmount;
	private int paymentPeriodFrom;
	private int paymentPeriodTo;
	private Integer lastDayAcceptPay;
	private int plusDay;
	private Integer overDueFee;
	private Date createdDate;
	private BigDecimal amtToDecrYourLoan;
	private BigDecimal monthlyInterest;
	private BigDecimal totalOnAMonth;
	private BigDecimal advisoryFee;
	private BigDecimal serviceFee;
	private BigDecimal extFeeIfIndPayBefore;
	private BigDecimal totalPayIfSettleRequest;
	private Integer dayMustPay;

	public TblLoanBill() {
	}

	public TblLoanBill(int loanId, long loanRemainAmount, int paymentPeriodFrom, int paymentPeriodTo, int plusDay,
			Date createdDate) {
		this.loanId = loanId;
		this.loanRemainAmount = loanRemainAmount;
		this.paymentPeriodFrom = paymentPeriodFrom;
		this.paymentPeriodTo = paymentPeriodTo;
		this.plusDay = plusDay;
		this.createdDate = createdDate;
	}

	public TblLoanBill(int loanId, long loanRemainAmount, int paymentPeriodFrom, int paymentPeriodTo,
			Integer lastDayAcceptPay, int plusDay, Integer overDueFee, Date createdDate, BigDecimal amtToDecrYourLoan,
			BigDecimal monthlyInterest, BigDecimal totalOnAMonth, BigDecimal advisoryFee, BigDecimal serviceFee,
			BigDecimal extFeeIfIndPayBefore, BigDecimal totalPayIfSettleRequest, Integer dayMustPay) {
		this.loanId = loanId;
		this.loanRemainAmount = loanRemainAmount;
		this.paymentPeriodFrom = paymentPeriodFrom;
		this.paymentPeriodTo = paymentPeriodTo;
		this.lastDayAcceptPay = lastDayAcceptPay;
		this.plusDay = plusDay;
		this.overDueFee = overDueFee;
		this.createdDate = createdDate;
		this.amtToDecrYourLoan = amtToDecrYourLoan;
		this.monthlyInterest = monthlyInterest;
		this.totalOnAMonth = totalOnAMonth;
		this.advisoryFee = advisoryFee;
		this.serviceFee = serviceFee;
		this.extFeeIfIndPayBefore = extFeeIfIndPayBefore;
		this.totalPayIfSettleRequest = totalPayIfSettleRequest;
		this.dayMustPay = dayMustPay;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bill_id", unique = true, nullable = false)
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	@Column(name = "loan_id", nullable = false)
	public int getLoanId() {
		return this.loanId;
	}

	public void setLoanId(int loanId) {
		this.loanId = loanId;
	}

	@Column(name = "loan_remain_amount", nullable = false, precision = 10, scale = 0)
	public long getLoanRemainAmount() {
		return this.loanRemainAmount;
	}

	public void setLoanRemainAmount(long loanRemainAmount) {
		this.loanRemainAmount = loanRemainAmount;
	}

	@Column(name = "payment_period_from", nullable = false)
	public int getPaymentPeriodFrom() {
		return this.paymentPeriodFrom;
	}

	public void setPaymentPeriodFrom(int paymentPeriodFrom) {
		this.paymentPeriodFrom = paymentPeriodFrom;
	}

	@Column(name = "payment_period_to", nullable = false)
	public int getPaymentPeriodTo() {
		return this.paymentPeriodTo;
	}

	public void setPaymentPeriodTo(int paymentPeriodTo) {
		this.paymentPeriodTo = paymentPeriodTo;
	}

	@Column(name = "last_day_accept_pay")
	public Integer getLastDayAcceptPay() {
		return this.lastDayAcceptPay;
	}

	public void setLastDayAcceptPay(Integer lastDayAcceptPay) {
		this.lastDayAcceptPay = lastDayAcceptPay;
	}

	@Column(name = "plus_day", nullable = false)
	public int getPlusDay() {
		return this.plusDay;
	}

	public void setPlusDay(int plusDay) {
		this.plusDay = plusDay;
	}

	@Column(name = "over_due_fee")
	public Integer getOverDueFee() {
		return this.overDueFee;
	}

	public void setOverDueFee(Integer overDueFee) {
		this.overDueFee = overDueFee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "amt_to_decr_your_loan", precision = 20, scale = 0)
	public BigDecimal getAmtToDecrYourLoan() {
		return this.amtToDecrYourLoan;
	}

	public void setAmtToDecrYourLoan(BigDecimal amtToDecrYourLoan) {
		this.amtToDecrYourLoan = amtToDecrYourLoan;
	}

	@Column(name = "monthly_interest", precision = 20, scale = 0)
	public BigDecimal getMonthlyInterest() {
		return this.monthlyInterest;
	}

	public void setMonthlyInterest(BigDecimal monthlyInterest) {
		this.monthlyInterest = monthlyInterest;
	}

	@Column(name = "total_on_a_month", precision = 20, scale = 0)
	public BigDecimal getTotalOnAMonth() {
		return this.totalOnAMonth;
	}

	public void setTotalOnAMonth(BigDecimal totalOnAMonth) {
		this.totalOnAMonth = totalOnAMonth;
	}

	@Column(name = "advisory_fee", precision = 20, scale = 0)
	public BigDecimal getAdvisoryFee() {
		return this.advisoryFee;
	}

	public void setAdvisoryFee(BigDecimal advisoryFee) {
		this.advisoryFee = advisoryFee;
	}

	@Column(name = "service_fee", precision = 20, scale = 0)
	public BigDecimal getServiceFee() {
		return this.serviceFee;
	}

	public void setServiceFee(BigDecimal serviceFee) {
		this.serviceFee = serviceFee;
	}

	@Column(name = "ext_fee_if_ind_pay_before", precision = 20, scale = 0)
	public BigDecimal getExtFeeIfIndPayBefore() {
		return this.extFeeIfIndPayBefore;
	}

	public void setExtFeeIfIndPayBefore(BigDecimal extFeeIfIndPayBefore) {
		this.extFeeIfIndPayBefore = extFeeIfIndPayBefore;
	}

	@Column(name = "total_pay_if_settle_request", precision = 20, scale = 0)
	public BigDecimal getTotalPayIfSettleRequest() {
		return this.totalPayIfSettleRequest;
	}

	public void setTotalPayIfSettleRequest(BigDecimal totalPayIfSettleRequest) {
		this.totalPayIfSettleRequest = totalPayIfSettleRequest;
	}

	@Column(name = "day_must_pay")
	public Integer getDayMustPay() {
		return this.dayMustPay;
	}

	public void setDayMustPay(Integer dayMustPay) {
		this.dayMustPay = dayMustPay;
	}

}
