package vn.com.payment.entities;
// Generated May 16, 2021 2:41:23 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblLoanReqDetail generated by hbm2java
 */
@Entity
@Table(name = "tbl_loan_req_detail", catalog = "db_fintech")
public class TblLoanReqDetail implements java.io.Serializable {

	private Integer reqDetailId;
	private int loanId;
	private int productId;
	private String productName;
	private Integer importFrom;
	private Integer manufactureDate;
	private long expectAmount;
	private int borrowerId;
	private Long approvedAmount;
	private Date createdDate;
	private Date editedDate;
	private Integer disbursementDate;

	public TblLoanReqDetail() {
	}

	public TblLoanReqDetail(int loanId, int productId, long expectAmount, int borrowerId, Date createdDate,
			Date editedDate) {
		this.loanId = loanId;
		this.productId = productId;
		this.expectAmount = expectAmount;
		this.borrowerId = borrowerId;
		this.createdDate = createdDate;
		this.editedDate = editedDate;
	}

	public TblLoanReqDetail(int loanId, int productId, String productName, Integer importFrom, Integer manufactureDate,
			long expectAmount, int borrowerId, Long approvedAmount, Date createdDate, Date editedDate,
			Integer disbursementDate) {
		this.loanId = loanId;
		this.productId = productId;
		this.productName = productName;
		this.importFrom = importFrom;
		this.manufactureDate = manufactureDate;
		this.expectAmount = expectAmount;
		this.borrowerId = borrowerId;
		this.approvedAmount = approvedAmount;
		this.createdDate = createdDate;
		this.editedDate = editedDate;
		this.disbursementDate = disbursementDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "req_detail_id", unique = true, nullable = false)
	public Integer getReqDetailId() {
		return this.reqDetailId;
	}

	public void setReqDetailId(Integer reqDetailId) {
		this.reqDetailId = reqDetailId;
	}

	@Column(name = "loan_id", nullable = false)
	public int getLoanId() {
		return this.loanId;
	}

	public void setLoanId(int loanId) {
		this.loanId = loanId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "product_name", length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "import_from")
	public Integer getImportFrom() {
		return this.importFrom;
	}

	public void setImportFrom(Integer importFrom) {
		this.importFrom = importFrom;
	}

	@Column(name = "manufacture_date")
	public Integer getManufactureDate() {
		return this.manufactureDate;
	}

	public void setManufactureDate(Integer manufactureDate) {
		this.manufactureDate = manufactureDate;
	}

	@Column(name = "expect_amount", nullable = false, precision = 10, scale = 0)
	public long getExpectAmount() {
		return this.expectAmount;
	}

	public void setExpectAmount(long expectAmount) {
		this.expectAmount = expectAmount;
	}

	@Column(name = "borrower_id", nullable = false)
	public int getBorrowerId() {
		return this.borrowerId;
	}

	public void setBorrowerId(int borrowerId) {
		this.borrowerId = borrowerId;
	}

	@Column(name = "approved_amount", precision = 10, scale = 0)
	public Long getApprovedAmount() {
		return this.approvedAmount;
	}

	public void setApprovedAmount(Long approvedAmount) {
		this.approvedAmount = approvedAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edited_date", nullable = false, length = 19)
	public Date getEditedDate() {
		return this.editedDate;
	}

	public void setEditedDate(Date editedDate) {
		this.editedDate = editedDate;
	}

	@Column(name = "disbursement_date")
	public Integer getDisbursementDate() {
		return this.disbursementDate;
	}

	public void setDisbursementDate(Integer disbursementDate) {
		this.disbursementDate = disbursementDate;
	}

}
