package vn.com.payment.entities;
// Generated 25-May-2021 21:43:38 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblLoanRequestAskAns generated by hbm2java
 */
@Entity
@Table(name = "tbl_loan_request_ask_ans", catalog = "db_fintech")
public class TblLoanRequestAskAns implements java.io.Serializable {

	private Integer QAId;
	private int loanId;
	private String QAThamDinh1;
	private String QAThamDinh2;
	private Float thamDinh1Rate;
	private Float thamDinh2Rate;

	public TblLoanRequestAskAns() {
	}

	public TblLoanRequestAskAns(int loanId) {
		this.loanId = loanId;
	}

	public TblLoanRequestAskAns(int loanId, String QAThamDinh1, String QAThamDinh2, Float thamDinh1Rate,
			Float thamDinh2Rate) {
		this.loanId = loanId;
		this.QAThamDinh1 = QAThamDinh1;
		this.QAThamDinh2 = QAThamDinh2;
		this.thamDinh1Rate = thamDinh1Rate;
		this.thamDinh2Rate = thamDinh2Rate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "q_a_id", unique = true, nullable = false)
	public Integer getQAId() {
		return this.QAId;
	}

	public void setQAId(Integer QAId) {
		this.QAId = QAId;
	}

	@Column(name = "loan_id", nullable = false)
	public int getLoanId() {
		return this.loanId;
	}

	public void setLoanId(int loanId) {
		this.loanId = loanId;
	}

	@Column(name = "q_a_tham_dinh_1")
	public String getQAThamDinh1() {
		return this.QAThamDinh1;
	}

	public void setQAThamDinh1(String QAThamDinh1) {
		this.QAThamDinh1 = QAThamDinh1;
	}

	@Column(name = "q_a_tham_dinh_2")
	public String getQAThamDinh2() {
		return this.QAThamDinh2;
	}

	public void setQAThamDinh2(String QAThamDinh2) {
		this.QAThamDinh2 = QAThamDinh2;
	}

	@Column(name = "tham_dinh1_rate", precision = 12, scale = 0)
	public Float getThamDinh1Rate() {
		return this.thamDinh1Rate;
	}

	public void setThamDinh1Rate(Float thamDinh1Rate) {
		this.thamDinh1Rate = thamDinh1Rate;
	}

	@Column(name = "tham_dinh2_rate", precision = 12, scale = 0)
	public Float getThamDinh2Rate() {
		return this.thamDinh2Rate;
	}

	public void setThamDinh2Rate(Float thamDinh2Rate) {
		this.thamDinh2Rate = thamDinh2Rate;
	}

}
