package vn.com.payment.entities;
// Generated Jun 6, 2021 1:19:10 AM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblLoanBill generated by hbm2java
 */
@Entity
@Table(name = "tbl_loan_bill", catalog = "db_fintech")
public class TblLoanBill implements java.io.Serializable {

	private Integer billId;
	private int loanId;
	private long loanRemainAmount;
	private int paymentPeriodFrom;
	private int paymentPeriodTo;
	private Integer lastDayAcceptPay;
	private int plusDay;
	private Integer overDueFee;
	private Date createdDate;
	private BigDecimal amtToDecrYourLoan;
	private BigDecimal monthlyInterest;
	private BigDecimal totalOnAMonth;
	private BigDecimal advisoryFee;
	private BigDecimal serviceFee;
	private BigDecimal extFeeIfIndPayBefore;
	private BigDecimal totalPayIfSettleRequest;
	private Integer dayMustPay;
	private Integer billStatus;
	private Integer billPaymentStatus;
	private Date paymentDate;
	private Long paymentAmt;
	private String billCollectBy;
	private Integer isASpecialPayment;
	private String comment;
	private Integer overDueDay;
	private Integer billIndex;

	public TblLoanBill() {
	}

	public TblLoanBill(int loanId, long loanRemainAmount, int paymentPeriodFrom, int paymentPeriodTo, int plusDay,
			Date createdDate) {
		this.loanId = loanId;
		this.loanRemainAmount = loanRemainAmount;
		this.paymentPeriodFrom = paymentPeriodFrom;
		this.paymentPeriodTo = paymentPeriodTo;
		this.plusDay = plusDay;
		this.createdDate = createdDate;
	}

	public TblLoanBill(int loanId, long loanRemainAmount, int paymentPeriodFrom, int paymentPeriodTo,
			Integer lastDayAcceptPay, int plusDay, Integer overDueFee, Date createdDate, BigDecimal amtToDecrYourLoan,
			BigDecimal monthlyInterest, BigDecimal totalOnAMonth, BigDecimal advisoryFee, BigDecimal serviceFee,
			BigDecimal extFeeIfIndPayBefore, BigDecimal totalPayIfSettleRequest, Integer dayMustPay, Integer billStatus,
			Integer billPaymentStatus, Date paymentDate, Long paymentAmt, String billCollectBy,
			Integer isASpecialPayment, String comment, Integer overDueDay, Integer billIndex) {
		this.loanId = loanId;
		this.loanRemainAmount = loanRemainAmount;
		this.paymentPeriodFrom = paymentPeriodFrom;
		this.paymentPeriodTo = paymentPeriodTo;
		this.lastDayAcceptPay = lastDayAcceptPay;
		this.plusDay = plusDay;
		this.overDueFee = overDueFee;
		this.createdDate = createdDate;
		this.amtToDecrYourLoan = amtToDecrYourLoan;
		this.monthlyInterest = monthlyInterest;
		this.totalOnAMonth = totalOnAMonth;
		this.advisoryFee = advisoryFee;
		this.serviceFee = serviceFee;
		this.extFeeIfIndPayBefore = extFeeIfIndPayBefore;
		this.totalPayIfSettleRequest = totalPayIfSettleRequest;
		this.dayMustPay = dayMustPay;
		this.billStatus = billStatus;
		this.billPaymentStatus = billPaymentStatus;
		this.paymentDate = paymentDate;
		this.paymentAmt = paymentAmt;
		this.billCollectBy = billCollectBy;
		this.isASpecialPayment = isASpecialPayment;
		this.comment = comment;
		this.overDueDay = overDueDay;
		this.billIndex = billIndex;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bill_id", unique = true, nullable = false)
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	@Column(name = "loan_id", nullable = false)
	public int getLoanId() {
		return this.loanId;
	}

	public void setLoanId(int loanId) {
		this.loanId = loanId;
	}

	@Column(name = "loan_remain_amount", nullable = false, precision = 10, scale = 0)
	public long getLoanRemainAmount() {
		return this.loanRemainAmount;
	}

	public void setLoanRemainAmount(long loanRemainAmount) {
		this.loanRemainAmount = loanRemainAmount;
	}

	@Column(name = "payment_period_from", nullable = false)
	public int getPaymentPeriodFrom() {
		return this.paymentPeriodFrom;
	}

	public void setPaymentPeriodFrom(int paymentPeriodFrom) {
		this.paymentPeriodFrom = paymentPeriodFrom;
	}

	@Column(name = "payment_period_to", nullable = false)
	public int getPaymentPeriodTo() {
		return this.paymentPeriodTo;
	}

	public void setPaymentPeriodTo(int paymentPeriodTo) {
		this.paymentPeriodTo = paymentPeriodTo;
	}

	@Column(name = "last_day_accept_pay")
	public Integer getLastDayAcceptPay() {
		return this.lastDayAcceptPay;
	}

	public void setLastDayAcceptPay(Integer lastDayAcceptPay) {
		this.lastDayAcceptPay = lastDayAcceptPay;
	}

	@Column(name = "plus_day", nullable = false)
	public int getPlusDay() {
		return this.plusDay;
	}

	public void setPlusDay(int plusDay) {
		this.plusDay = plusDay;
	}

	@Column(name = "over_due_fee")
	public Integer getOverDueFee() {
		return this.overDueFee;
	}

	public void setOverDueFee(Integer overDueFee) {
		this.overDueFee = overDueFee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "amt_to_decr_your_loan", precision = 20, scale = 0)
	public BigDecimal getAmtToDecrYourLoan() {
		return this.amtToDecrYourLoan;
	}

	public void setAmtToDecrYourLoan(BigDecimal amtToDecrYourLoan) {
		this.amtToDecrYourLoan = amtToDecrYourLoan;
	}

	@Column(name = "monthly_interest", precision = 20, scale = 0)
	public BigDecimal getMonthlyInterest() {
		return this.monthlyInterest;
	}

	public void setMonthlyInterest(BigDecimal monthlyInterest) {
		this.monthlyInterest = monthlyInterest;
	}

	@Column(name = "total_on_a_month", precision = 20, scale = 0)
	public BigDecimal getTotalOnAMonth() {
		return this.totalOnAMonth;
	}

	public void setTotalOnAMonth(BigDecimal totalOnAMonth) {
		this.totalOnAMonth = totalOnAMonth;
	}

	@Column(name = "advisory_fee", precision = 20, scale = 0)
	public BigDecimal getAdvisoryFee() {
		return this.advisoryFee;
	}

	public void setAdvisoryFee(BigDecimal advisoryFee) {
		this.advisoryFee = advisoryFee;
	}

	@Column(name = "service_fee", precision = 20, scale = 0)
	public BigDecimal getServiceFee() {
		return this.serviceFee;
	}

	public void setServiceFee(BigDecimal serviceFee) {
		this.serviceFee = serviceFee;
	}

	@Column(name = "ext_fee_if_ind_pay_before", precision = 20, scale = 0)
	public BigDecimal getExtFeeIfIndPayBefore() {
		return this.extFeeIfIndPayBefore;
	}

	public void setExtFeeIfIndPayBefore(BigDecimal extFeeIfIndPayBefore) {
		this.extFeeIfIndPayBefore = extFeeIfIndPayBefore;
	}

	@Column(name = "total_pay_if_settle_request", precision = 20, scale = 0)
	public BigDecimal getTotalPayIfSettleRequest() {
		return this.totalPayIfSettleRequest;
	}

	public void setTotalPayIfSettleRequest(BigDecimal totalPayIfSettleRequest) {
		this.totalPayIfSettleRequest = totalPayIfSettleRequest;
	}

	@Column(name = "day_must_pay")
	public Integer getDayMustPay() {
		return this.dayMustPay;
	}

	public void setDayMustPay(Integer dayMustPay) {
		this.dayMustPay = dayMustPay;
	}

	@Column(name = "bill_status")
	public Integer getBillStatus() {
		return this.billStatus;
	}

	public void setBillStatus(Integer billStatus) {
		this.billStatus = billStatus;
	}

	@Column(name = "bill_payment_status")
	public Integer getBillPaymentStatus() {
		return this.billPaymentStatus;
	}

	public void setBillPaymentStatus(Integer billPaymentStatus) {
		this.billPaymentStatus = billPaymentStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_date", length = 19)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "payment_amt", precision = 11, scale = 0)
	public Long getPaymentAmt() {
		return this.paymentAmt;
	}

	public void setPaymentAmt(Long paymentAmt) {
		this.paymentAmt = paymentAmt;
	}

	@Column(name = "bill_collect_by")
	public String getBillCollectBy() {
		return this.billCollectBy;
	}

	public void setBillCollectBy(String billCollectBy) {
		this.billCollectBy = billCollectBy;
	}

	@Column(name = "is_a_special_payment")
	public Integer getIsASpecialPayment() {
		return this.isASpecialPayment;
	}

	public void setIsASpecialPayment(Integer isASpecialPayment) {
		this.isASpecialPayment = isASpecialPayment;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "over_due_day")
	public Integer getOverDueDay() {
		return this.overDueDay;
	}

	public void setOverDueDay(Integer overDueDay) {
		this.overDueDay = overDueDay;
	}

	@Column(name = "bill_index")
	public Integer getBillIndex() {
		return this.billIndex;
	}

	public void setBillIndex(Integer billIndex) {
		this.billIndex = billIndex;
	}

}
