package vn.com.payment.entities;
// Generated Jun 5, 2021 4:20:29 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblLoanSponsorMapp generated by hbm2java
 */
@Entity
@Table(name = "tbl_loan_sponsor_mapp", catalog = "db_fintech")
public class TblLoanSponsorMapp implements java.io.Serializable {

	private Integer loanSponsorMappId;
	private int loanId;
	private int sponsorId;
	private Date createdDate;
	private Date disbursementDate;
	private Integer disbursementStatus;
	private Date entryExpireTime;

	public TblLoanSponsorMapp() {
	}

	public TblLoanSponsorMapp(int loanId, int sponsorId) {
		this.loanId = loanId;
		this.sponsorId = sponsorId;
	}

	public TblLoanSponsorMapp(int loanId, int sponsorId, Date createdDate, Date disbursementDate,
			Integer disbursementStatus, Date entryExpireTime) {
		this.loanId = loanId;
		this.sponsorId = sponsorId;
		this.createdDate = createdDate;
		this.disbursementDate = disbursementDate;
		this.disbursementStatus = disbursementStatus;
		this.entryExpireTime = entryExpireTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "loan_sponsor_mapp_id", unique = true, nullable = false)
	public Integer getLoanSponsorMappId() {
		return this.loanSponsorMappId;
	}

	public void setLoanSponsorMappId(Integer loanSponsorMappId) {
		this.loanSponsorMappId = loanSponsorMappId;
	}

	@Column(name = "loan_id", nullable = false)
	public int getLoanId() {
		return this.loanId;
	}

	public void setLoanId(int loanId) {
		this.loanId = loanId;
	}

	@Column(name = "sponsor_id", nullable = false)
	public int getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(int sponsorId) {
		this.sponsorId = sponsorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "disbursement_date", length = 19)
	public Date getDisbursementDate() {
		return this.disbursementDate;
	}

	public void setDisbursementDate(Date disbursementDate) {
		this.disbursementDate = disbursementDate;
	}

	@Column(name = "disbursement_status")
	public Integer getDisbursementStatus() {
		return this.disbursementStatus;
	}

	public void setDisbursementStatus(Integer disbursementStatus) {
		this.disbursementStatus = disbursementStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "entry_expire_time", length = 19)
	public Date getEntryExpireTime() {
		return this.entryExpireTime;
	}

	public void setEntryExpireTime(Date entryExpireTime) {
		this.entryExpireTime = entryExpireTime;
	}

}
