package vn.com.payment.entities;
// Generated 15-May-2021 09:07:14 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblProduct generated by hbm2java
 */
@Entity
@Table(name = "tbl_product", catalog = "db_fintech")
public class TblProduct implements java.io.Serializable {

	private Integer productId;
	private String productName;
	private String productCode;
	private int productType;
	private Integer productBrandId;
	private Long brandnewPrice;
	private Long loanPrice;
	private Date createdDate;
	private Integer registeredTime;

	public TblProduct() {
	}

	public TblProduct(String productName, String productCode, int productType, Date createdDate) {
		this.productName = productName;
		this.productCode = productCode;
		this.productType = productType;
		this.createdDate = createdDate;
	}

	public TblProduct(String productName, String productCode, int productType, Integer productBrandId,
			Long brandnewPrice, Long loanPrice, Date createdDate, Integer registeredTime) {
		this.productName = productName;
		this.productCode = productCode;
		this.productType = productType;
		this.productBrandId = productBrandId;
		this.brandnewPrice = brandnewPrice;
		this.loanPrice = loanPrice;
		this.createdDate = createdDate;
		this.registeredTime = registeredTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_id", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "product_name", nullable = false, length = 50)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_code", nullable = false, length = 50)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "product_type", nullable = false)
	public int getProductType() {
		return this.productType;
	}

	public void setProductType(int productType) {
		this.productType = productType;
	}

	@Column(name = "product_brand_id")
	public Integer getProductBrandId() {
		return this.productBrandId;
	}

	public void setProductBrandId(Integer productBrandId) {
		this.productBrandId = productBrandId;
	}

	@Column(name = "brandnew_price", precision = 10, scale = 0)
	public Long getBrandnewPrice() {
		return this.brandnewPrice;
	}

	public void setBrandnewPrice(Long brandnewPrice) {
		this.brandnewPrice = brandnewPrice;
	}

	@Column(name = "loan_price", precision = 10, scale = 0)
	public Long getLoanPrice() {
		return this.loanPrice;
	}

	public void setLoanPrice(Long loanPrice) {
		this.loanPrice = loanPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "registered_time")
	public Integer getRegisteredTime() {
		return this.registeredTime;
	}

	public void setRegisteredTime(Integer registeredTime) {
		this.registeredTime = registeredTime;
	}

}
