package vn.com.payment.entities;
// Generated May 27, 2021 12:09:14 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblQuestions generated by hbm2java
 */
@Entity
@Table(name = "tbl_questions", catalog = "db_fintech")
public class TblQuestions implements java.io.Serializable {

	private Integer questionId;
	private String questionContent;
	private String questionShortDesc;
	private Integer questionType;
	private Integer stepOfProcess;
	private String correctAnswears;
	private Integer requireAnswear;
	private Integer activeStatus;
	private String availableAnswear;

	public TblQuestions() {
	}

	public TblQuestions(String questionContent) {
		this.questionContent = questionContent;
	}

	public TblQuestions(String questionContent, String questionShortDesc, Integer questionType, Integer stepOfProcess,
			String correctAnswears, Integer requireAnswear, Integer activeStatus, String availableAnswear) {
		this.questionContent = questionContent;
		this.questionShortDesc = questionShortDesc;
		this.questionType = questionType;
		this.stepOfProcess = stepOfProcess;
		this.correctAnswears = correctAnswears;
		this.requireAnswear = requireAnswear;
		this.activeStatus = activeStatus;
		this.availableAnswear = availableAnswear;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "question_id", unique = true, nullable = false)
	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	@Column(name = "question_content", nullable = false, length = 500)
	public String getQuestionContent() {
		return this.questionContent;
	}

	public void setQuestionContent(String questionContent) {
		this.questionContent = questionContent;
	}

	@Column(name = "question_short_desc")
	public String getQuestionShortDesc() {
		return this.questionShortDesc;
	}

	public void setQuestionShortDesc(String questionShortDesc) {
		this.questionShortDesc = questionShortDesc;
	}

	@Column(name = "question_type")
	public Integer getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(Integer questionType) {
		this.questionType = questionType;
	}

	@Column(name = "step_of_process")
	public Integer getStepOfProcess() {
		return this.stepOfProcess;
	}

	public void setStepOfProcess(Integer stepOfProcess) {
		this.stepOfProcess = stepOfProcess;
	}

	@Column(name = "correct_answears", length = 500)
	public String getCorrectAnswears() {
		return this.correctAnswears;
	}

	public void setCorrectAnswears(String correctAnswears) {
		this.correctAnswears = correctAnswears;
	}

	@Column(name = "require_answear")
	public Integer getRequireAnswear() {
		return this.requireAnswear;
	}

	public void setRequireAnswear(Integer requireAnswear) {
		this.requireAnswear = requireAnswear;
	}

	@Column(name = "active_status")
	public Integer getActiveStatus() {
		return this.activeStatus;
	}

	public void setActiveStatus(Integer activeStatus) {
		this.activeStatus = activeStatus;
	}

	@Column(name = "available_answear", length = 500)
	public String getAvailableAnswear() {
		return this.availableAnswear;
	}

	public void setAvailableAnswear(String availableAnswear) {
		this.availableAnswear = availableAnswear;
	}

}
